import dns from 'node:dns';
dns.setServers(["8.8.8.8","8.8.4.4"]);

import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


const outfit=Outfit({
  subsets:['latin']
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${outfit.className}  h-full antialiased`}
    >
      <body className="min-h-full bg-base-200 flex flex-col">
        <Navbar></Navbar>
        {children}
        
      </body>
    </html>
  );
}
